### ISSUE TITLE
Vault not found on make file line 14

### ISSUE THREAD

**Issue by ENate** [hashicorp-dev-advocates/workshop-vault-for-developers#7]
Thanks for the example. I want to access pki secrets from vault via docker compose in a spring cloud gateway distributed application. I looked at the example you provided in this repo  and did;
```
cd docker-compose
make setup
```
After building, I saw the following:

```
scripts/setup.sh: line 14: vault: command not found
scripts/setup.sh: line 14: vault: command not found
scripts/setup.sh: line 14: vault: command not found
scripts/setup.sh: line 14: vault: command not found
scripts/setup.sh: line 14: vault: command not found
```
Will this output be okay to see? I also tried to check the example on vault agent and got the following:

```
Container workshop-vault-for-developers-vault-agent-1   Waiting                                                                                                             16.0s 
 ✔ Container workshop-vault-for-developers-payments-app-1  Created 
```
And the Agent service finally stops building. Why is the agent not able to build? Thanks

**Comment by joatmon08** [comment]
Hi @ENate. I'll update the README, but you will need the [Vault CLI](https://developer.hashicorp.com/vault/install) installed on your local machine in order to set up Vault.
